name: Flake8 Linter

on: [push]
 # pull_request:
  #  branches:
   #   - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Flake8
        run: python -m pip install flake8
        
      - name: Run Flake8 and Save Output
        run: |
          cd $GITHUB_WORKSPACE
          flake8 | tee flake8-output.txt
          echo "" >> flake8-output.txt
          cat flake8-output.txt >> append.txt
          mv append.txt flake8-output.txt
          
      - name: Upload flake8 results
        id: upload_results
        uses: actions/upload-artifact@v3
        with:
          name: flake8-results
          path: ${{ github.workspace }}/flake8-output.txt
          
      - name: Check Output Content and Fail Test
        run: |
          file_size=$(stat -c %s ${{ github.workspace }}/flake8-output.txt)
          if [ "$file_size" -gt 1024 ]; then
            echo "Error: flake8-output.txt is not empty."
          else
            echo "flake8-output.txt is empty."
          fi

      - name: Fail Workflow if Output is not Empty
        if: steps.upload_results.outputs.artifact_size > 0
        run: exit 1
