name: Flake8 Linter

on: [push]
  #pull_request:
   # branches:
     # - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Flake8
        run: python -m pip install flake8
        
      - name: Run Flake8 and Save Output
        run: |
          cd $GITHUB_WORKSPACE
          flake8 | tee flake8-output.txt
          echo "" >> flake8-output.txt
          cat flake8-output.txt >> append.txt
          mv append.txt flake8-output.txt
          
      - name: Upload flake8 results
        id: upload_results
        uses: actions/upload-artifact@v3
        with:
          name: flake8-results
          path: ${{ github.workspace }}/flake8-output.txt
          
      - name: Check Output Size and Fail Test
        run: |
          file_size=$(stat -c %s ${{ github.workspace }}/flake8-output.txt)
          if [ "$file_size" -gt 1 ]; then
            echo "Error: flake8-output.txt size exceeds 1 byte."
            exit 1
          else
            echo "flake8-output.txt size is within limits."
            exit 0
          fi
