name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      # Install pip and flake8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install --upgrade flake8
      - name: Test with flake8
        run: |
         flake8 --exclude=.github/workflows > buildlog.txt
      - name: Upload flake8 results
        uses: actions/upload-artifact@v3
        with:
          name: flake8-results
          path: buildlog.txt  
