name: Flake8 Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Flake8
        run: python -m pip install flake8
        
      - name: Run Flake8 and Save Output
        run: |
          cd $GITHUB_WORKSPACE
          flake8 | tee flake8-output.txt
          echo "" >> flake8-output.txt
          cat flake8-output.txt >> append.txt
          mv append.txt flake8-output.txt
          
      - name: Upload flake8 results
        uses: actions/upload-artifact@v3
        with:
          name: flake8-results
          path: ${{ github.workspace }}/flake8-output.txt  

      - name: Configure Git
        env:
          GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        run: |
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USERNAME}"

      - name: Commit Flake8 Output
        run: |
          mv flake8-output.txt $GITHUB_WORKSPACE/flake8-output.txt
          git add flake8-output.txt
          git commit -m "Add Flake8 output"
          git push
          
